# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/objectnav: mp3d
  - /habitat/task/lab_sensors:
    - gps_sensor
    - compass_sensor
  - _self_

habitat:
  environment:
    max_episode_steps: 2000
    iterator_options:
      max_scene_repeat_steps: 50000
      shuffle: False
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.0
            max_depth: 10.0
    forward_step_size: 0.25
    turn_angle: 30
    tilt_angle: 15
    action_space_config: "v1"
    habitat_sim_v0:
      allow_sliding: True
      gpu_device_id: 0
  task:
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: VIEW_POINTS
      success:
        type: Success
        success_distance: 0.25
      spl:
        type: SPL
      oracle_success:
        type: OracleSuccess
      oracle_navigation_error:
        type: OracleNavigationError
    actions:
      stop:
        type: StopAction
        agent_index: 0
      move_forward:
        type: MoveForwardAction
        agent_index: 0
      turn_left:
        type: TurnLeftAction
        agent_index: 0
      turn_right:
        type: TurnRightAction
        agent_index: 0
      look_up:
        type: LookUpAction
        agent_index: 0
      look_down:
        type: LookDownAction
        agent_index: 0

  dataset:
    type: dialog
    split: unseen_mini
    scenes_dir: projects/VL-LN-Bench/scene_datasets/
    data_path: projects/VL-LN-Bench/raw_data/mp3d/val_unseen/val_unseen_iion.json.gz
